# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jrp < Formula
  desc ""
  homepage ""
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/yanosea/jrp/releases/download/v1.1.0/jrp_Darwin_x86_64.tar.gz"
      sha256 "d9c9e9cb208cb344511a3e4329ca9279f095e9ae6b5c632c469a04f41fdf2123"

      def install
        bin.install "jrp"
      end
    end
    on_arm do
      url "https://github.com/yanosea/jrp/releases/download/v1.1.0/jrp_Darwin_arm64.tar.gz"
      sha256 "f5250c20d734fcb05bf40b9f7a7780fdb10cd9c7fed47a77727518ad788a90a0"

      def install
        bin.install "jrp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yanosea/jrp/releases/download/v1.1.0/jrp_Linux_x86_64.tar.gz"
        sha256 "ae3939220ad9088ff2bae20887b3c89779a426cd075166096acd111142c502e5"

        def install
          bin.install "jrp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yanosea/jrp/releases/download/v1.1.0/jrp_Linux_arm64.tar.gz"
        sha256 "4a9dd053adfda4d654eee3ddb9ddcdf2fdb08c8367c4b6e9940c4dda8680e5c7"

        def install
          bin.install "jrp"
        end
      end
    end
  end
end
