# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mindnum < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/yanosea/mindnum/releases/download/v0.1.0/mindnum_Darwin_x86_64.tar.gz"
      sha256 "7a87444d59f82fc7cb33abeb7232237c7aa3a314aa9e1e925d2519187ff9c8b9"

      def install
        bin.install "mindnum"
      end
    end
    on_arm do
      url "https://github.com/yanosea/mindnum/releases/download/v0.1.0/mindnum_Darwin_arm64.tar.gz"
      sha256 "48c7379e907eed5b469f12db32e645856fd98bd471568e09ebd5c1b3ee24fcae"

      def install
        bin.install "mindnum"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yanosea/mindnum/releases/download/v0.1.0/mindnum_Linux_x86_64.tar.gz"
        sha256 "fd29759a2f3ca7413bba98239159c52f255ab0a6985751cd4301d198a99f1126"

        def install
          bin.install "mindnum"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yanosea/mindnum/releases/download/v0.1.0/mindnum_Linux_arm64.tar.gz"
        sha256 "9b195ae58a30036e56496e7488ab82ca21feb2c19db2833c3bfc68dd67aa77ca"

        def install
          bin.install "mindnum"
        end
      end
    end
  end
end
