# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mindnum < Formula
  desc ""
  homepage ""
  version "2.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yanosea/mindnum/releases/download/v2.0.3/mindnum_Darwin_x86_64.tar.gz"
      sha256 "a21e78543449f71ab71a7641b9a6ba848f24c006d1d3844f123ab01c132b4c55"

      def install
        bin.install "mindnum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yanosea/mindnum/releases/download/v2.0.3/mindnum_Darwin_arm64.tar.gz"
      sha256 "f53410dcac8970d82e5a20481bfc37b9b598c474fdffa8550eff8e20c68c5c43"

      def install
        bin.install "mindnum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yanosea/mindnum/releases/download/v2.0.3/mindnum_Linux_x86_64.tar.gz"
      sha256 "9ca56788c818b98b564e7ab00048b6b0e1772797937be9fe616dbf85cf58822a"
      def install
        bin.install "mindnum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yanosea/mindnum/releases/download/v2.0.3/mindnum_Linux_arm64.tar.gz"
      sha256 "3cdbf2c75b4ad00c25dd5fca11c4fb0db14d78247ed98e3396bcba48f04f26e5"
      def install
        bin.install "mindnum"
      end
    end
  end
end
