# This file was generated by GoReleaser. DO NOT EDIT.
cask "jrp" do
  name "jrp"
  desc ""
  homepage ""
  version "2.1.19"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jrp"

  on_macos do
    on_intel do
      url "https://github.com/yanosea/jrp/releases/download/v#{version}/jrp_Darwin_x86_64.tar.gz"
      sha256 "0d56cb76e23b2cf21c73298032f7e8e442c7722a203009c043ea091d869e48b7"
    end
    on_arm do
      url "https://github.com/yanosea/jrp/releases/download/v#{version}/jrp_Darwin_arm64.tar.gz"
      sha256 "11aebc0025d211857ffbc32f7e9b5c87694087dd5a59d7b4462cebdba0bea7f4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yanosea/jrp/releases/download/v#{version}/jrp_Linux_x86_64.tar.gz"
      sha256 "f905818003c331db16f98e5463226ea5433684ab453f38a929c420d09b6bb0fe"
    end
    on_arm do
      url "https://github.com/yanosea/jrp/releases/download/v#{version}/jrp_Linux_arm64.tar.gz"
      sha256 "e6f6183c253942f010f258f9a7c3f5cdc56dc7979aa4f38347c97c4b663b643d"
    end
  end

  # No zap stanza required
end
