# This file was generated by GoReleaser. DO NOT EDIT.
cask "mindnum" do
  name "mindnum"
  desc ""
  homepage ""
  version "2.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mindnum"

  on_macos do
    on_intel do
      url "https://github.com/yanosea/mindnum/releases/download/v#{version}/mindnum_Darwin_x86_64.tar.gz"
      sha256 "941c95d6c632741e7ea3bcd5db4545201ed5249272cd29d50084ce4db60e5769"
    end
    on_arm do
      url "https://github.com/yanosea/mindnum/releases/download/v#{version}/mindnum_Darwin_arm64.tar.gz"
      sha256 "de931e8151c3dad040627d6a2740308cc88109bd1f98cfacfb5dc261b77a66cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yanosea/mindnum/releases/download/v#{version}/mindnum_Linux_x86_64.tar.gz"
      sha256 "b4913d644b60d693bc0bd0a38bf8bac5d4e21e02ee061413e01a2428b3bb8c99"
    end
    on_arm do
      url "https://github.com/yanosea/mindnum/releases/download/v#{version}/mindnum_Linux_arm64.tar.gz"
      sha256 "0790f1797f1c63e80ae700cee2afe1f2af995592e61114bd3985697dfdf8e5dd"
    end
  end

  # No zap stanza required
end
