# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotlike" do
  name "spotlike"
  desc ""
  homepage ""
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spotlike"

  on_macos do
    on_intel do
      url "https://github.com/yanosea/spotlike/releases/download/v#{version}/spotlike_Darwin_x86_64.tar.gz"
      sha256 "e1a4962a3c85b48ac2a0016e9d3f1f30886ffdfa60194ae2f36e46389dd241d5"
    end
    on_arm do
      url "https://github.com/yanosea/spotlike/releases/download/v#{version}/spotlike_Darwin_arm64.tar.gz"
      sha256 "cdc2f6414bb3546ea4364387ba84bbcb1dcb30dbdbd7146dd23567f2e2da1213"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yanosea/spotlike/releases/download/v#{version}/spotlike_Linux_x86_64.tar.gz"
      sha256 "ae8914d8d5b7ce13ded05633b3b8e3facbac649600b8e76948f1114b12c7b9a1"
    end
    on_arm do
      url "https://github.com/yanosea/spotlike/releases/download/v#{version}/spotlike_Linux_arm64.tar.gz"
      sha256 "9c52679cecd4f8e70055427c71b7f50713f7da6564cdd3bbb6a66aab4f474c81"
    end
  end

  # No zap stanza required
end
